### ISSUE TITLE
architecture of application

### ISSUE THREAD

**Issue by Joonior1990** [picpoint/picpoint#1]
I. To change structure your app to view: (you can choose plurar or single names of folders)
For example:
- maket(s) (your psd)
- image(s) (img, png, svg, etc)
- view(s) or templates (html - files)
- style(s) (css, or preprocessors - scss, less, etc)
- script(s) (js)
or
- login
   - index.html
   - style.css
   - script.js
   - images
      - .img
      - .png ...
   - makets ...
- contacts
   - files of contacts pages

II. To change names of files.
For example:
loginPage.template.html
loginPage.style.css
loginPage.script.js

**Comment by picpoint** [comment]
поправил структуру

**Comment by Joonior1990** [comment]
Why do you save the name of folder "css" -> you use image (not img) makets (not psd) and in this case you solved to save the short name of folder.

I think that change name of folder to "style" will be better then save short name.
