### ISSUE TITLE
Include css library from reset default styles

### ISSUE THREAD

**Issue by Joonior1990** [picpoint/picpoint#2]
Include the public library "normalize.css" or similar of it. To use for it service npm (create package.json and include there the library name . Exept this library from the repository).  

Links: [normalize.css](http://nicolasgallagher.com/), [npm](https://www.npmjs.com/) 

Sum: you should create 2 files: package.json(file of configuration your project) .gitignore (there include the dependency folder - node_modules. There will be normalize.css);

p.s. don't forget include library into html, be sure that all right.

**Comment by picpoint** [comment]
include normalize.css

**Comment by Joonior1990** [comment]
Done partially. package.json wasn't creating.
